container_nodes:
    main_collection: container_nodes

container_nodes_tags:
    main_collection: container_nodes
    sub_collection: tags
    foreign_key: container_node_id

container_images_tags:
    main_collection: container_images
    sub_collection: tags
    foreign_key: container_image_id

volume_attachments:
    main_collection: volume_attachments

volumes:
    main_collection: volumes

volume_types:
    main_collection: volume_types

vms:
    main_collection: vms

sources:
    main_collection: sources
    service: SOURCES

container_groups:
    main_collection: container_groups

containers:
    main_collection: container_groups
    sub_collection: containers
    foreign_key: container_group_id

container_resource_quotas:
    main_collection: container_resource_quotas

container_projects:
    main_collection: container_projects

container_images:
    main_collection: container_images

flavors:
    main_collection: flavors
