aiops-volume-type-validation:
  - container_nodes
  - container_nodes_tags
  - vms
  - sources
  - volume_attachments
  - volumes
  - volume_types

aiops-idle-cost-savings:
  - container_nodes
  - container_nodes_tags
  - vms
  - sources
  - container_groups
  - containers
  - container_resource_quotas
  - container_projects
  - flavors

aiops-instance-type-validation:
  - container_nodes
  - container_nodes_tags
  - container_images
  - container_images_tags
  - container_groups
  - containers
  - vms
  - sources
